AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'vendor/bundle/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
Rails:
  Enabled: true
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
ClassLength:
  Enabled: false
